### ISSUE TITLE
NoClassDefFoundError in android 4.4 even with multidex enabled

### ISSUE THREAD

**Issue by EsteveAguilera** [JakeWharton/ThreeTenABP#136]
We have a **Flutter** app that is using the [Flutter local notifications package](https://github.com/MaikuB/flutter_local_notifications)

We got crash reports for **Android 4.4** devices and opened an issue [https://github.com/MaikuB/flutter_local_notifications/issues/1502](https://github.com/MaikuB/flutter_local_notifications/issues/1502), but it's related to this library

```
Fatal Exception: java.lang.NoClassDefFoundError: e.g.a.b
       at com.jakewharton.threetenabp.AndroidThreeTen.init(AndroidThreeTen.java)
       at com.jakewharton.threetenabp.AndroidThreeTen.init(AndroidThreeTen.java)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.initAndroidThreeTen(FlutterLocalNotificationsPlugin.java)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.rescheduleNotifications(FlutterLocalNotificationsPlugin.java)
       at com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver.onReceive(ScheduledNotificationBootReceiver.java)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2624)
       at android.app.ActivityThread.access$1800(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5345)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

I've already checked the closed issue #39 but we already had **multidex enabled** as it is suggested to be the fix, but the crash is still there.

```groovy
dependencies {
    def multidex_version = "2.0.1"
    implementation "androidx.multidex:multidex:$multidex_version"
```

**Comment by JakeWharton** [comment]
Based on the stacktrace it's either failing to load `AssetsZoneRulesInitializer` from this library or `ZoneRulesInitializer` from ThreeTenBP. A deobfuscated stacktrace would tell you.

That being said, there's really not a whole lot I can do here since the problem does not appear to be in the library but in however your APK is built. You can use APK inspector inside Android Studio to see which dex files contain the offending class which cannot be loaded. If it's in anything but the first dex then you indeed have a problem with your legacy multidex setup. Are you extending from `MultidexApplication` or whatever the recommended type is?

**Comment by EsteveAguilera** [comment]
You were right @JakeWharton, the issue was on our side. 

The `MultidexApplication` hint pointed us in the right direction, that we were missing some multidex configuration. 
We are using this on a Flutter App, so we can not change the `Application` base class, but we use the `MultiDex.install(this)` method as suggested in the [documentation](https://developer.android.com/studio/build/multidex) and it's working now.

Thanks for your answer!
