### ISSUE TITLE
IllegalStateException: TZDB.dat missing from assets

### ISSUE THREAD

**Issue by sockeqwe** [JakeWharton/ThreeTenABP#24]
Hi,
I'm writing a unit test with Robolectric 3 (read some data from a sqlite database use `Instant` for Dates / Times)

The problem is that Robolectric is not able to open the file:
```
java.lang.IllegalStateException: TZDB.dat missing from assets.
	at com.jakewharton.threetenabp.AndroidThreeTen.init(AndroidThreeTen.java:24)
	at com.droidcon.App.onCreate(App.kt:15)
	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:140)
	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:433)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:240)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.io.FileNotFoundException: build/intermediates/bundles/debug/assets/org/threeten/bp/TZDB.dat (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.robolectric.res.FileFsFile.getInputStream(FileFsFile.java:78)
	at org.robolectric.shadows.ShadowAssetManager.open(ShadowAssetManager.java:168)
	at android.content.res.AssetManager.open(AssetManager.java)
	at com.jakewharton.threetenabp.AndroidThreeTen.init(AndroidThreeTen.java:21)
	at com.droidcon.App.onCreate(App.kt:15)
	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:140)
	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:433)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:240)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	... 1 more

java.lang.RuntimeException: java.lang.IllegalStateException: TZDB.dat missing from assets.

	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:244)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.IllegalStateException: TZDB.dat missing from assets.
	at com.jakewharton.threetenabp.AndroidThreeTen.init(AndroidThreeTen.java:24)
	at com.droidcon.App.onCreate(App.kt:15)
	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:140)
	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:433)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:240)
	... 18 more
Caused by: java.io.FileNotFoundException: build/intermediates/bundles/debug/assets/org/threeten/bp/TZDB.dat (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.robolectric.res.FileFsFile.getInputStream(FileFsFile.java:78)
	at org.robolectric.shadows.ShadowAssetManager.open(ShadowAssetManager.java:168)
	at android.content.res.AssetManager.open(AssetManager.java)
	at com.jakewharton.threetenabp.AndroidThreeTen.init(AndroidThreeTen.java:21)
	at com.droidcon.App.onCreate(App.kt:15)
	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:140)
	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:433)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:240)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	... 1 more
```

Basically I wanted to use Robolectric's `RuntimeEnvironment.application` to get a context to for SqliteOpenHelper.

My App class is just initializing `AndroidThreeTen`:
```kotlin
class App : Application() {
  override fun onCreate() {
    super.onCreate()
    AndroidThreeTen.init(this)
  }
}
```

Do you think this is a Robolectric issue? If yes, I will open an issue there

**Comment by JakeWharton** [comment]
This is a Robolectric bug. Either report to them or switch to use the
normal ThreeTenBP in your unit tests. Or both!

**Comment by JakeWharton** [comment]
https://github.com/JakeWharton/ThreeTenABP/issues/14#issuecomment-142049959

**Comment by sockeqwe** [comment]
Thanks

**Comment by krystianpe** [comment]
Same thing happens in AS 2.2 Preview 3 with instant run enabled (with AS 2.1.x it worked fine).

**Comment by amyu** [comment]
```kotlin
    private fun initThreeTen() {
        try {
            AndroidThreeTen.init(this)
        } catch (e: IllegalStateException) {
            //https://github.com/JakeWharton/ThreeTenABP/issues/24
        }
    }
```

**Comment by JakeWharton** [comment]
No, that is terrible. Crashing is the appropriate reaction to this.

**Comment by tymm** [comment]
What helped me to workaround this issue is to put `TZDB.dat` into `test/assets/org/threeten/bp/`.

**Comment by shaunkawano** [comment]
I had the same issue before so I chose to switch to use normal ThreeTenBP for testing.
But using AS 3.0 stable version and roboolectric 3.5.1 together, the issue no longer appears to me. I commented out the ThreeTenBP dependency and it worked. Can't identify the clear solution or what solved the issue in my case but this issue could be closed?
