### ISSUE TITLE
NoClassDefFoundError in android 4.4?

### ISSUE THREAD

**Issue by davidgarciaanton** [JakeWharton/ThreeTenABP#39]
I'm getting a NoClassDefFoundError when initializing the library in Application#onCreate

The stacktrace I'm getting is:

```
java.lang.NoClassDefFoundError: org.threeten.bp.zone.TzdbZoneRulesProvider
                      at com.jakewharton.threetenabp.AndroidThreeTen.init(AndroidThreeTen.java:28)
                      at com.jakewharton.threetenabp.AndroidThreeTen.init(AndroidThreeTen.java:16)
                      at com.crumbit.crumbitapp.App.onCreate(App.java:99)
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4344)
                      at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:5017)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                      at dalvik.system.NativeStart.main(Native Method)
```

I'm trying to find out why, but meanwhile I have a clue I'm just opening this to see if somebody else has a clue on that, guess that mostly has to do with build process.

**Comment by heitorcolangelo** [comment]
Hey David.
How did you solve this issue?

**Comment by timrijckaert** [comment]
Yes how? 👍

**Comment by danieltigse** [comment]
I have the same error, even with multidex enabled. How do you solved?

**Comment by VerachadW** [comment]
One possible solution is Disable Instant Run. This is work for me.

**Comment by maragues-kolibree** [comment]
In my case, since I develop for *minSdk 21* I hadn't added the multidex dependency 
```
compile "com.android.support:multidex:1.0.2"
```

Adding it and extending from extended from MultiDexApplication immediately fixed the issue

See https://developer.android.com/studio/build/multidex.html#mdex-pre-l

**Comment by andriipanasiuk** [comment]
I had the same issue if I used 
`classpath 'com.android.tools.build:gradle:3.1.0-alpha08'` in my project's `build.gradle`.
After I updated it to 
`classpath 'com.android.tools.build:gradle:3.1.0-alpha09'`
the issue was fixed.
