### ISSUE TITLE
org.threeten.bp.zone.ZoneRulesException: Unable to load TZDB time-zone rules

### ISSUE THREAD

**Issue by jaredsburrows** [JakeWharton/ThreeTenABP#40]
## Version:

1.0.3
## Exception:

```
java.lang.RuntimeException: Unable to create application App: org.threeten.bp.zone.ZoneRulesException: Unable to load TZDB time-zone rules
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4809)
    at android.app.ActivityThread.access$1600(ActivityThread.java:154)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:234)
    at android.app.ActivityThread.main(ActivityThread.java:5526)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: org.threeten.bp.zone.ZoneRulesException: Unable to load TZDB time-zone rules
    at org.threeten.bp.zone.TzdbZoneRulesProvider.<init>(TzdbZoneRulesProvider.java:124)
    at com.jakewharton.threetenabp.AndroidThreeTen.init(AndroidThreeTen.java:22)
    at <>.onCreate(ApplicationState.java:162)
    at
Caused by: java.io.EOFException
    at java.io.DataInputStream.readByte(DataInputStream.java:77)
    at org.threeten.bp.zone.TzdbZoneRulesProvider.loadData(TzdbZoneRulesProvider.java:233)
    at org.threeten.bp.zone.TzdbZoneRulesProvider.load(TzdbZoneRulesProvider.java:212)
    at org.threeten.bp.zone.TzdbZoneRulesProvider.<init>(TzdbZoneRulesProvider.java:122)
    ... 14 more
```

**Comment by jaredsburrows** [comment]
@JakeWharton Should I move this to the `threeten` github?

**Comment by jaredsburrows** [comment]
Any update on this?

**Comment by jaredsburrows** [comment]
Closing this as I am not seeing the issue anymore.
