### ISSUE TITLE
org.threeten.bp.zone.ZoneRulesException: Unknown time-zone ID: Asia/Hanoi

### ISSUE THREAD

**Issue by jaredsburrows** [JakeWharton/ThreeTenABP#41]
## Version:

1.0.3

## Exception:

```
org.threeten.bp.zone.ZoneRulesException: Unknown time-zone ID: Asia/Hanoi
	at org.threeten.bp.zone.ZoneRulesProvider.getProvider(ZoneRulesProvider.java:178)
	at org.threeten.bp.zone.ZoneRulesProvider.getRules(ZoneRulesProvider.java:133)
	at org.threeten.bp.ZoneRegion.ofId(ZoneRegion.java:143)
	at org.threeten.bp.ZoneId.of(ZoneId.java:357)
	at org.threeten.bp.ZoneId.of(ZoneId.java:285)
	at org.threeten.bp.ZoneId.systemDefault(ZoneId.java:244)
	at<>.(DateAgoFormatter.java:45)
	at <>.(ThreadCardViewCreator.java:533)
	at <>.(ThreadCardViewCreator.java:324)
	at <>.(ThreadCardViewCreator.java:283)
	at <>.(ThreadCardViewCreator.java:71)
	at <>.(Card.java:30)
	at <>.(BaseFeedAdapter.java:91)
	at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java)
	at android.widget.AbsListView.obtainView(AbsListView.java)
	at android.widget.ListView.makeAndAddView(ListView.java)
	at android.widget.ListView.fillDown(ListView.java)
	at android.widget.ListView.fillFromTop(ListView.java)
	at android.widget.ListView.layoutChildren(ListView.java)
	at android.widget.AbsListView.onLayout(AbsListView.java)
	at android.view.View.layout(View.java)
	at android.view.ViewGroup.layout(ViewGroup.java)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java)
	at android.widget.FrameLayout.onLayout(FrameLayout.java)
	at android.view.View.layout(View.java)
	at android.view.ViewGroup.layout(ViewGroup.java)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java)
	at android.widget.FrameLayout.onLayout(FrameLayout.java)
	at android.view.View.layout(View.java)
	at android.view.ViewGroup.layout(ViewGroup.java)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:598)
	at android.view.View.layout(View.java)
	at android.view.ViewGroup.layout(ViewGroup.java)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java)
	at android.widget.FrameLayout.onLayout(FrameLayout.java)
	at android.view.View.layout(View.java)
	at android.view.ViewGroup.layout(ViewGroup.java)
	at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:122)
	at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1192)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:814)
	at android.view.View.layout(View.java)
	at android.view.ViewGroup.layout(ViewGroup.java)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1191)
	at android.view.View.layout(View.java)
	at android.view.ViewGroup.layout(ViewGroup.java)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java)
	at android.widget.FrameLayout.onLayout(FrameLayout.java)
	at android.view.View.layout(View.java)
	at android.view.ViewGroup.layout(ViewGroup.java)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java)
	at android.widget.FrameLayout.onLayout(FrameLayout.java)
	at android.view.View.layout(View.java)
	at android.view.ViewGroup.layout(ViewGroup.java)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java)
	at android.widget.FrameLayout.onLayout(FrameLayout.java)
	at android.view.View.layout(View.java)
	at android.view.ViewGroup.layout(ViewGroup.java)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java)
	at android.widget.LinearLayout.onLayout(LinearLayout.java)
	at android.view.View.layout(View.java)
	at android.view.ViewGroup.layout(ViewGroup.java)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java)
	at android.widget.FrameLayout.onLayout(FrameLayout.java)
	at android.view.View.layout(View.java)
	at android.view.ViewGroup.layout(ViewGroup.java)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java)
	at android.view.Choreographer.doCallbacks(Choreographer.java)
	at android.view.Choreographer.doFrame(Choreographer.java)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java)
	at android.os.Handler.handleCallback(Handler.java)
	at android.os.Handler.dispatchMessage(Handler.java)
	at android.os.Looper.loop(Looper.java)
	at android.app.ActivityThread.main(ActivityThread.java)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
```

**Comment by JakeWharton** [comment]
Not a problem with this library which just packages [ThreeTenBP][1] for Android. A quick look at the TZDB though and that doesn't appear to be a supported zone.

**Comment by jaredsburrows** [comment]
@JakeWharton Thanks. Let me report it there.
