### ISSUE TITLE
Android Studio preview?

### ISSUE THREAD

**Issue by AndreasBackx** [JakeWharton/ThreeTenABP#42]
Is there a way to make ThreeTenABP work in Android Studio's Preview tab? Initialising the library when in edit mode still raises the errors below in the preview tab.

I've tried @tymm's solution for #24 to no avail. Any suggestions?

Error after building the project:

```
java.io.FileNotFoundException: Asset file: org/threeten/bp/TZDB.dat
    at android.content.res.AssetManager.open(AssetManager.java:354)
    at android.content.res.AssetManager.open(AssetManager.java:321)
    at com.jakewharton.threetenabp.AndroidThreeTen.init(AndroidThreeTen.java:27)
    at some.package.name.view.SomeCustomView.<init>(SomeCustomView.kt:61)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:465)
    at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:172)
    at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:105)
    at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:186)
    at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:334)
    at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:345)
    at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:245)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
    at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)
    at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
    at android.view.LayoutInflater_Delegate.parseInclude(LayoutInflater_Delegate.java:197)
    at android.view.LayoutInflater.parseInclude(LayoutInflater.java:902)
    at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:854)
    at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
    at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)
    at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
    at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:324)
    at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:429)
    at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:389)
    at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:548)
    at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:533)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:966)
    at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:533)
    at com.android.tools.idea.rendering.RenderTask.lambda$inflate$53(RenderTask.java:659)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

Error after refreshing the layout:

```
org.threeten.bp.zone.ZoneRulesException: No time-zone data files registered
    at org.threeten.bp.zone.ZoneRulesProvider.getProvider(ZoneRulesProvider.java:176)
    at org.threeten.bp.zone.ZoneRulesProvider.getRules(ZoneRulesProvider.java:133)
    at org.threeten.bp.ZoneRegion.ofId(ZoneRegion.java:143)
    at org.threeten.bp.ZoneId.of(ZoneId.java:357)
    at org.threeten.bp.ZoneId.of(ZoneId.java:285)
    at org.threeten.bp.ZoneId.systemDefault(ZoneId.java:244)
    at org.threeten.bp.Clock.systemDefaultZone(Clock.java:137)
    at org.threeten.bp.OffsetDateTime.now(OffsetDateTime.java:175)
    at some.package.name.view.SomeCustomView.updateItems(SomeCustomView.kt:77)
    at some.package.name.view.SomeCustomView.<init>(SomeCustomView.kt:72)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:465)
    at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:172)
    at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:105)
    at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:186)
    at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:334)
    at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:345)
    at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:245)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
    at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)
    at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
    at android.view.LayoutInflater_Delegate.parseInclude(LayoutInflater_Delegate.java:197)
    at android.view.LayoutInflater.parseInclude(LayoutInflater.java:902)
    at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:854)
    at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
    at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)
    at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
    at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:324)
    at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:429)
    at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:389)
    at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:548)
    at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:533)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:966)
    at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:533)
    at com.android.tools.idea.rendering.RenderTask.lambda$inflate$53(RenderTask.java:659)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

Initialisation used in the custom view:

``` kotlin
if(isInEditMode)
    AndroidThreeTen.init(context)
```

**Comment by kotucz** [comment]
You can avoid using `now()` in edit mode. You probably can work with fixed data for preview

**Comment by AndreasBackx** [comment]
@kotucz yes, that's what I did. but I still reported it just in case.

**Comment by JakeWharton** [comment]
I think you would have to declare the dependency as `apk` and then declare regular ThreeTenBP as `compileOnly`. Not sure what classpath layoutlib uses.

**Comment by JakeWharton** [comment]
Of course that would also prevent referencing our init...

**Comment by AndreasBackx** [comment]
Unfortunately I am no longer working on the project so I cannot take it for a spin. How come this error occurs in the edit mode?

**Comment by JakeWharton** [comment]
It cannot access assets because it runs on the JVM inside the IDE. One
might consider that a bug though...

**Comment by JakeWharton** [comment]
I have upstreamed this as a feature request to support asset loading in layoutlib: https://issuetracker.google.com/issues/78324332.

**Comment by AndreasBackx** [comment]
Great, I'll try to keep an eye on it. Thanks for filing the feature request.

**Comment by JakeWharton** [comment]
This works for me:
```java
public final class CustomView extends TextView {
  public CustomView(Context context, AttributeSet attrs) {
    super(context, attrs);
    if (isInEditMode()) {
      AndroidThreeTen.init(context);
      setText("Test: " + LocalDateTime.now());
    }
  }
}
```
```xml
<?xml version="1.0" encoding="utf-8"?>
<com.example.CustomView
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    />
```
![screen shot 2019-01-23 at 11 56 35 am](https://user-images.githubusercontent.com/66577/51623101-f65b8000-1f05-11e9-8dba-aa979c23b801.png)

**Comment by AndreasBackx** [comment]
Thanks! I'll keep it in mind for future project. I appreciate you reporting back.
