### ISSUE TITLE
ThreeTenABP as JAR?

### ISSUE THREAD

**Issue by cleemansen** [JakeWharton/ThreeTenABP#62]
Hello,

I am working w/ multiple gradle modules in my android app. One of them is a pure `java` module.
As I understand it a Java-Module can not depend on a aar-dependency. Trying to integrate _ThreeTenADB_ into my Java-Module fails w/ build-error:
> Error:Module 'xxxxxx' depends on one or more Android Libraries but is a jar

- Is ThreeTenADB available packaged as JAR?
- Can I convert a AAR to a JAR?
- Any other ideas how to mix android- and java-modules witch depends both to a state of the art time implementation?

Thanks!

**Comment by JakeWharton** [comment]
You can depend on the normal https://github.com/ThreeTen/threetenbp library and then use a Gradle [resolution strategy dependency substitution](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html) to replace that dependency with the ABP one for Android modules (or just the app module).

**Comment by cleemansen** [comment]
Thank you for that hint! I really appreciate it!

I added to the `app/build.gradle`:
```
configurations {
  compile.resolutionStrategy {
    dependencySubstitution {
      substitute module('org.threeten:threetenbp:1.3.6') with module('com.jakewharton.threetenabp:threetenabp:1.0.5')
    }
  }
}
```

Gradle build is now fine. 
Unfortunately my app doesn't start anymore. I am not sure if it is related to my first question. My I ask you again for any tips w/ the following exception during startup:

```
Caused by: org.threeten.bp.zone.ZoneRulesException: Unable to register zone as one already registered with that ID: Asia/Aden, currently loading from provider: TZDB
                                                                                     at org.threeten.bp.zone.ZoneRulesProvider.registerProvider0(ZoneRulesProvider.java:205)
                                                                                     at org.threeten.bp.zone.ZoneRulesProvider.registerProvider(ZoneRulesProvider.java:190)
                                                                                     at com.jakewharton.threetenabp.AndroidThreeTen.init(AndroidThreeTen.java:40)
                                                                                     at com.jakewharton.threetenabp.AndroidThreeTen.init(AndroidThreeTen.java:16)
```
